(in-package "ACL2")

(include-book "atomic")
(include-book "binop")
(include-book "case-of")
(include-book "cons")
(include-book "exprs")
(include-book "fun-call")
(include-book "functions")
(include-book "if")
(include-book "local-call")
(include-book "match")
(include-book "remote-call")
(include-book "tuple")
(include-book "unop")